name: Deploy Book Client

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm ci
          cd aws-cdk && npm ci

      - name: Build Angular app
        run: |
          npm run build --production

      - name: Deploy with CDK
        run: |
          cd aws-cdk && npm run deploy

      - name: Clean up
        run: |
          npm prune --production
